dependencies:
  - name: mixer
    version: 1.1.0
  - name: prometheus
    version: 1.1.0
    condition: prometheus.enabled
  - name: servicegraph
    version: 1.1.0
    condition: servicegraph.enabled
  - name: tracing
    version: 1.1.0
    condition: tracing.enabled
  - name: kiali
    version: 1.1.0
    condition: kiali.enabled
