apiVersion: v1
kind: Service
metadata:
  name: istio-citadel11
  namespace: {{ .Release.Namespace }}
  labels:
    app: citadel
    istio: citadel
spec:
  ports:
    - name: grpc-citadel
      port: 8060
      targetPort: 8060
      protocol: TCP
    - name: http-monitoring
      port: 9093
  selector:
    app: citadel
