image: galley
replicaCount: 1

resources:
  requests:
    cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

# TODO: Galley appears to use the mesh config - need to find which fields are used and need to be configured.
mesh: {}

# TODO: Global values used in Galley - may not be needed in global.
global:
  configValidation: true
  controlPlaneSecurityEnabled: true
  # priorityClassName
  # tag must be set
