apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tracing
  namespace: {{ .Release.Namespace }}
spec:
  host: tracing.{{ .Release.Namespace }}
  trafficPolicy:
    tls:
      mode: DISABLE
