#
# mixer configuration
#
image: mixer

env:
  GODEBUG: gctrace=2

enabled: true
replicaCount: 1
autoscaleEnabled: true
autoscaleMin: 1
autoscaleMax: 5
cpu:
  targetAverageUtilization: 80

resources:
  requests:
    cpu: 900m
    memory: 1G

podAnnotations: {}

adapters:
  prometheus:
    metricsExpiryDuration: 10m
