#
# mixer configuration
#
image: mixer

env:
  GODEBUG: gctrace=2

istio-policy:
  enabled: true
  replicaCount: 1
  autoscaleEnabled: true
  autoscaleMin: 1
  autoscaleMax: 5
  cpu:
    targetAverageUtilization: 80

istio-telemetry:
  enabled: true
  replicaCount: 1
  autoscaleEnabled: true
  autoscaleMin: 1
  autoscaleMax: 5
  cpu:
    targetAverageUtilization: 80

podAnnotations: {}

adapters:
  prometheus:
    metricsExpiryDuration: 10m
