apiVersion: v1
kind: Service
metadata:
  name: egressgateway
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $val := .Values.serviceAnnotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    app: egressgateway
    chart: egressgateway
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: egressgateway
  ports:
    {{- range $key, $val := .Values.ports }}
    -
      {{- range $pkey, $pval := $val }}
      {{ $pkey}}: {{ $pval }}
      {{- end }}
    {{- end }}
---
