apiVersion: v1
kind: Service
metadata:
  name: istio-telemetry
  namespace: {{ .Release.Namespace }}
  labels:
    app: istio-telemetry
spec:
  ports:
  - name: grpc-mixer
    port: 9091
  - name: grpc-mixer-mtls
    port: 15004
  - name: http-monitoring
    port: 9093
  - name: prometheus
    port: 42422
  selector:
    app: istio-telemetry
