## Requires citadel istio-sidecar-injector-service-account.istio-env11:istio-sidecar-injector.istio-env11.svc

#
# sidecar-injector webhook configuration
#
replicaCount: 1
image: sidecar_injector
enableNamespacesByDefault: false
istio_cni:
  enabled: false



# Global contains common fields, used in several Istio components.
# It is possible for each component to use different a setup profile.
global:
  istioNamespace: istio-pilot11

  hub: gcr.io/istio-release
  #tag: master-latest-daily
  #tag: release-1.0-latest-daily
  tag: release-1.1-latest-daily
  # imagePullPolicy is applied to istio control plane components.
  imagePullPolicy: Always


  proxy_init:
    # Base name for the proxy_init container, used to configure iptables.
    # Note that it is different from istio1.0 - same image was used.
    image: proxyv2

  proxy:
    #includeIPRanges: ""
    #excludeIPRanges: ""
    #statusPort
    enableCoreDump: false
    image: proxyv2
    tracer: zipkin
    # Default port for Pilot agent health checks. A value of 0 will disable health checking.
    statusPort: 15020

    # The initial delay for readiness probes in seconds.
    readinessInitialDelaySeconds: 1

    # The period between readiness probes.
    readinessPeriodSeconds: 2

    # The number of successive failed probes before indicating readiness failure.
    readinessFailureThreshold: 30

    # DNS domain suffix for pilot proxy agent. Default value is "${POD_NAMESPACE}.svc.cluster.local".
    proxyDomain: ""

    # DNS domain suffix for pilot proxy discovery. Default value is "cluster.local".
    discoveryDomain: ""

    # Resources for the sidecar.
    resources:
      requests:
        cpu: 10m
      #  memory: 128Mi
      # limits:
      #   cpu: 100m
      #   memory: 128Mi

  sds:
    enabled: false

  # Configuration for each of the supported tracers
  tracer:
    # Configuration for envoy to send trace data to LightStep.
    # Disabled by default.
    # address: the <host>:<port> of the satellite pool
    # accessToken: required for sending data to the pool
    # secure: specifies whether data should be sent with TLS
    # cacertPath: the path to the file containing the cacert to use when verifying TLS. If secure is true, this is
    #   required. If a value is specified then a secret called "lightstep.cacert" must be created in the destination
    #   namespace with the key matching the base of the provided cacertPath and the value being the cacert itself.
    #
    lightstep:
      address: ""                # example: lightstep-satellite:443
      accessToken: ""            # example: abcdefg1234567
      secure: true               # example: true|false
      cacertPath: ""             # example: /etc/lightstep/cacert.pem
    zipkin:
      # Host:Port for reporting trace data in zipkin format. If not specified, will default to
      # zipkin service (port 9411) in the same namespace as the other istio components.
      address: ""

  arch:
    amd64: 2
    s390x: 2
    ppc64le: 2
