{{- if .Values.podDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: istio-ingress
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.podDisruptionBudget }}
  {{ include "podDisruptionBudget.spec" .Values.podDisruptionBudget }}
  {{- end }}
selector:
  matchLabels:
    app: ingressgateway
{{- end }}
