{{- if .Values.pilot.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-networks
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "istio.name" . }}
    chart: {{ template "istio.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  meshNetworks: |-
    networks: {}
    #
    # Example:
    #
    # networks:
    #   network1:
    #     endpoints:
    #     - fromCidr: "192.168.0.1/24"
    #     gateways:
    #     - address: 1.1.1.1
    #       port: 80
    #   network2:
    #     endpoints:
    #     - fromRegistry: reg1
    #     gateways:
    #     - registryServiceName: reg1
    #       port: 443
{{- end }}
