{{- if not .Values.global.omitSidecarInjectorConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-sidecar-injector
  namespace: {{ .Release.Namespace }}
  labels:
    app: sidecar-injector
    istio: sidecar-injector
data:
  # Mesh config used to generate the template. Template uses ProxyConfig to access it
  # TODO: do we really need it, just complicates thing - adding stuff directly seems cleaner
  # Either way a restart of the injector is needed.
  # Main use case would be adding directly a section of values.yaml, which can be overritten
  mesh: |-
   defaultConfig:
     #
     # TCP connection timeout between Envoy & the application, and between Envoys.
     connectTimeout: 10s
     #
     ### ADVANCED SETTINGS #############
     # Where should envoy's configuration be stored in the istio-proxy container
     configPath: "/etc/istio/proxy"
     # The pseudo service name used for Envoy.
     serviceCluster: istio-proxy
     # These settings that determine how long an old Envoy
     # process should be kept alive after an occasional reload.
     drainDuration: 45s
     parentShutdownDuration: 1m0s
     #
     # Port where Envoy listens (on local host) for admin commands
     # You can exec into the istio-proxy container in a pod and
     # curl the admin port (curl http://localhost:15000/) to obtain
     # diagnostic information from Envoy. See
     # https://lyft.github.io/envoy/docs/operations/admin.html
     # for more details
     proxyAdminPort: 15000
     #
     # Set concurrency to a specific number to control the number of Proxy worker threads.
     # If set to 0 (default), then start worker thread for each CPU thread/core.
     concurrency: {{ .Values.global.proxy.concurrency }}
     #
     {{- if eq .Values.global.proxy.tracer "lightstep" }}
     tracing:
       lightstep:
         # Address of the LightStep Satellite pool
         address: {{ .Values.global.tracer.lightstep.address }}
         # Access Token used to communicate with the Satellite pool
         accessToken: {{ .Values.global.tracer.lightstep.accessToken }}
         # Whether communication with the Satellite pool should be secure
         secure: {{ .Values.global.tracer.lightstep.secure }}
         # Path to the file containing the cacert to use when verifying TLS
         cacertPath: {{ .Values.global.tracer.lightstep.cacertPath }}
     {{- else if eq .Values.global.proxy.tracer "zipkin" }}
     tracing:
       zipkin:
         # Address of the Zipkin collector
       {{- if .Values.global.tracer.zipkin.address }}
         address: {{ .Values.global.tracer.zipkin.address }}
       {{- else }}
         address: zipkin.{{ .Release.Namespace }}:9411
       {{- end }}
     {{- end }}

   {{- if .Values.global.controlPlaneSecurityEnabled }}
     #
     # Mutual TLS authentication between sidecars and istio control plane.
     controlPlaneAuthPolicy: MUTUAL_TLS
     #
     # Address where istio Pilot service is running
     discoveryAddress: istio-pilot.{{ .Values.global.istioNamespace }}:15011
   {{- else }}
     #
     # Mutual TLS authentication between sidecars and istio control plane.
     controlPlaneAuthPolicy: NONE
     #
     # Address where istio Pilot service is running
     discoveryAddress: istio-pilot.{{ .Values.global.istioNamespace }}:15010
   {{- end }}

  config: |-
    policy: enabled
    template: |-
{{- if or (not .Values.istio_cni.enabled) .Values.global.proxy.enableCoreDump }}
      initContainers:
{{- if not .Values.istio_cni.enabled }}
      - name: istio-init
{{- if contains "/" .Values.global.proxy.image }}
        image: {{ "[[ annotation .ObjectMeta `sidecar.istio.io/proxyImage` " }} "{{ .Values.global.proxy.image }}" {{ " ]]" }}
{{- else }}
        image: {{ "[[ annotation .ObjectMeta `sidecar.istio.io/proxyImage` " }} "{{ .Values.global.hub }}/{{ .Values.global.proxy.image }}:{{ .Values.global.tag }}" {{ " ]]" }}
{{- end }}
        command:
        - "/usr/local/bin/istio-iptables.sh"
        - "-p"
        - {{ "[[ .MeshConfig.ProxyListenPort ]]" }}
        - "-u"
        - 1337
        - "-m"
        - {{ "[[ annotation .ObjectMeta `sidecar.istio.io/interceptionMode` .ProxyConfig.InterceptionMode ]]" }}
        - "-i"
        - {{ "\"[[ annotation .ObjectMeta `traffic.sidecar.istio.io/includeOutboundIPRanges` " }} "{{ .Values.global.proxy.includeIPRanges }}" {{ " ]]\"" }}
        - "-x"
        - {{ "\"[[ annotation .ObjectMeta `traffic.sidecar.istio.io/excludeOutboundIPRanges` " }} "{{ .Values.global.proxy.excludeIPRanges }}" {{ " ]]\"" }}
        - "-b"
        - {{ "\"[[ annotation .ObjectMeta `traffic.sidecar.istio.io/includeInboundPorts` (includeInboundPorts .Spec.Containers) ]]\"" }}
        - "-d"
        - {{ "\"[[ excludeInboundPort (annotation .ObjectMeta `status.sidecar.istio.io/port` " }} {{ .Values.global.proxy.statusPort }} {{ ") (annotation .ObjectMeta `traffic.sidecar.istio.io/excludeInboundPorts` " }} "{{ .Values.global.proxy.excludeInboundPorts }}" {{ ") ]]\"" }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 10m
            memory: 10Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          {{ if .Values.global.proxy.privileged }}
          privileged: true
          {{ end -}}
        restartPolicy: Always
{{- end }}
      {{ if eq .Values.global.proxy.enableCoreDump true }}
      - name: enable-core-dump
        args:
        - -c
        - sysctl -w kernel.core_pattern=/var/lib/istio/core.proxy && ulimit -c unlimited
        command:
          - /bin/sh
  {{- if contains "/" .Values.global.proxy_init.image }}
        image: "{{ .Values.global.proxy_init.image }}"
  {{- else }}
        image: "{{ .Values.global.hub }}/{{ .Values.global.proxy_init.image }}:{{ .Values.global.tag }}"
  {{- end }}
        imagePullPolicy: IfNotPresent
        resources: {}
        securityContext:
          privileged: true
      {{ end }}
{{- end }}
      containers:
      - name: istio-proxy
{{- if contains "/" .Values.global.proxy.image }}
        image: {{ "[[ annotation .ObjectMeta `sidecar.istio.io/proxyImage` " }} "{{ .Values.global.proxy.image }}" {{ " ]]" }}
{{- else }}
        image: {{ "[[ annotation .ObjectMeta `sidecar.istio.io/proxyImage` " }} "{{ .Values.global.hub }}/{{ .Values.global.proxy.image }}:{{ .Values.global.tag }}" {{ " ]]" }}
{{- end }}
        ports:
        - containerPort: 15090
          protocol: TCP
          name: http-envoy-prom
        args:
        - proxy
        - sidecar
{{- if .Values.global.proxy.proxyDomain }}
        - --domain
        - {{ .Values.global.proxy.proxyDomain }}
{{- end }}
        - --configPath
        - {{ "[[ .ProxyConfig.ConfigPath ]]" }}
        - --binaryPath
        - {{ "[[ .ProxyConfig.BinaryPath ]]" }}
        - --serviceCluster
        {{ "[[ if ne \"\" (index .ObjectMeta.Labels \"app\") -]]" }}
        - {{ "[[ index .ObjectMeta.Labels \"app\" ]].[[ valueOrDefault .DeploymentMeta.Namespace \"default\" ]]" }}
        {{ "[[ else -]]" }}
        - {{ "[[ valueOrDefault .DeploymentMeta.Name \"istio-proxy\" ]].[[ valueOrDefault .DeploymentMeta.Namespace \"default\" ]]" }}
        {{ "[[ end -]]" }}
        - --drainDuration
        - {{ "[[ formatDuration .ProxyConfig.DrainDuration ]]" }}
        - --parentShutdownDuration
        - {{ "[[ formatDuration .ProxyConfig.ParentShutdownDuration ]]" }}
        - --discoveryAddress
        - {{ "[[ .ProxyConfig.DiscoveryAddress ]]" }}
      {{- if eq .Values.global.proxy.tracer "lightstep" }}
        - --lightstepAddress
        - {{ "[[ .ProxyConfig.GetTracing.GetLightstep.GetAddress ]]" }}
        - --lightstepAccessToken
        - {{ "[[ .ProxyConfig.GetTracing.GetLightstep.GetAccessToken ]]" }}
        - --lightstepSecure={{ "[[ .ProxyConfig.GetTracing.GetLightstep.GetSecure ]]" }}
        - --lightstepCacertPath
        - {{ "[[ .ProxyConfig.GetTracing.GetLightstep.GetCacertPath ]]" }}
      {{- else if eq .Values.global.proxy.tracer "zipkin" }}
        - --zipkinAddress
        - {{ "[[ .ProxyConfig.GetTracing.GetZipkin.GetAddress ]]" }}
      {{- end }}
        - --connectTimeout
        - {{ "[[ formatDuration .ProxyConfig.ConnectTimeout ]]" }}
        - --proxyAdminPort
        - {{ "[[ .ProxyConfig.ProxyAdminPort ]]" }}
        {{ "[[ if gt .ProxyConfig.Concurrency 0 -]]" }}
        - --concurrency
        - {{ "[[ .ProxyConfig.Concurrency ]]" }}
        {{ "[[ end -]]" }}
        - --controlPlaneAuthPolicy
        - {{ "[[ annotation .ObjectMeta `sidecar.istio.io/controlPlaneAuthPolicy` .ProxyConfig.ControlPlaneAuthPolicy ]]" }}
          {{ "[[- if (ne (annotation .ObjectMeta `status.sidecar.istio.io/port` " }} {{ .Values.global.proxy.statusPort }} {{ ") \"0\") ]]" }}
        - --statusPort
        - {{ "[[ annotation .ObjectMeta `status.sidecar.istio.io/port` " }} {{ .Values.global.proxy.statusPort }} {{ " ]]" }}
        - --applicationPorts
        - {{ "\"[[ annotation .ObjectMeta `readiness.status.sidecar.istio.io/applicationPorts` (applicationPorts .Spec.Containers) ]]\"" }}
      {{ "[[- end ]]" }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ISTIO_META_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ISTIO_META_INTERCEPTION_MODE
          value: {{ "[[ or (index .ObjectMeta.Annotations \"sidecar.istio.io/interceptionMode\") .ProxyConfig.InterceptionMode.String ]]" }}
        {{- if .Values.global.proxy.network }}
        - name: ISTIO_META_NETWORK
          value: "{{ .Values.global.proxy.network }}"
        {{- end }}
        {{ "[[ if .ObjectMeta.Annotations ]]" }}
        - name: ISTIO_METAJSON_ANNOTATIONS
          value: |
                 {{ "[[ toJSON .ObjectMeta.Annotations ]]" }}
        {{ "[[ end ]]" }}
        {{ "[[ if .ObjectMeta.Labels ]]" }}
        - name: ISTIO_METAJSON_LABELS
          value: |
                 {{ "[[ toJSON .ObjectMeta.Labels ]]" }}
        {{ "[[ end ]]" }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        {{ "[[ if (ne (annotation .ObjectMeta `status.sidecar.istio.io/port` " }} {{ .Values.global.proxy.statusPort }} {{ ") \"0\") ]]" }}
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: {{ "[[ annotation .ObjectMeta `status.sidecar.istio.io/port` " }} {{ .Values.global.proxy.statusPort }} {{ " ]]" }}
          initialDelaySeconds: {{ "[[ annotation .ObjectMeta `readiness.status.sidecar.istio.io/initialDelaySeconds` " }} {{ .Values.global.proxy.readinessInitialDelaySeconds }} {{ " ]]" }}
          periodSeconds: {{ "[[ annotation .ObjectMeta `readiness.status.sidecar.istio.io/periodSeconds` " }} {{ .Values.global.proxy.readinessPeriodSeconds }} {{ " ]]" }}
          failureThreshold: {{ "[[ annotation .ObjectMeta `readiness.status.sidecar.istio.io/failureThreshold` " }} {{ .Values.global.proxy.readinessFailureThreshold }} {{ " ]]" }}
        {{- "[[- end ]]" }}
        securityContext:
          {{ if .Values.global.proxy.privileged }}
          privileged: true
          {{ end -}}
          {{- if ne .Values.global.proxy.enableCoreDump true }}
          readOnlyRootFilesystem: true
          {{- end }}
          {{ "[[ if eq (annotation .ObjectMeta `sidecar.istio.io/interceptionMode` .ProxyConfig.InterceptionMode) \"TPROXY\" -]]" }}
          capabilities:
            add:
            - NET_ADMIN
          runAsGroup: 1337
          {{ "[[ else -]]" }}
          runAsUser: 1337
          {{ "[[- end ]]" }}
        resources:
          {{ "[[ if (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyCPU`) -]]" }}
          requests:
            cpu: {{ "\"[[ index .ObjectMeta.Annotations `sidecar.istio.io/proxyCPU` ]]\"" }}
            memory: {{ "\"[[ index .ObjectMeta.Annotations `sidecar.istio.io/proxyMemory` ]]\"" }}
        {{ "[[ else -]]" }}
{{- if .Values.global.proxy.resources }}
{{ toYaml .Values.global.proxy.resources | indent 10 }}
{{- end }}
        {{ "[[ end -]]" }}
        volumeMounts:
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/certs/
          name: istio-certs
          readOnly: true
        {{ if .Values.global.sds.enabled }}
        - mountPath: /var/run/sds
          name: sds-uds-path
        {{ if .Values.global.sds.enableTokenMount }}
        - mountPath: /var/run/secrets/tokens
          name: istio-token
        {{- end }}
        {{- end }}
        {{ if and (eq .Values.global.proxy.tracer "lightstep") .Values.global.tracer.lightstep.cacertPath }}
        - mountPath: {{ "[[ directory .ProxyConfig.GetTracing.GetLightstep.GetCacertPath ]]" }}
          name: lightstep-certs
          readOnly: true
        {{- end }}
      volumes:
      {{ if .Values.global.sds.enabled }}
      - name: sds-uds-path
        hostPath:
          path: /var/run/sds
      {{ if .Values.global.sds.enableTokenMount }}
      - name: istio-token
        projected:
          sources:
          - serviceAccountToken:
              path: istio-token
              expirationSeconds: 43200
              audience: {{ .Values.global.trustDomain }}
      {{- end }}
      {{- end }}
      {{ if and (eq .Values.global.proxy.tracer "lightstep") .Values.global.tracer.lightstep.cacertPath }}
      - name: lightstep-certs
        secret:
          optional: true
          secretName: lightstep.cacert
      {{- end }}
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - name: istio-certs
        secret:
          optional: true
          {{ "[[ if eq .Spec.ServiceAccountName \"\" -]]" }}
          secretName: istio.default
          {{ "[[ else -]]" }}
          secretName: {{ "[[ printf \"istio.%s\" .Spec.ServiceAccountName ]]"  }}
          {{ "[[ end -]]" }}
{{- end }}
{{- if .Values.global.podDNSSearchNamespaces }}
      dnsConfig:
        searches:
          {{- range .Values.global.podDNSSearchNamespaces }}
          - {{ . }}
          {{- end }}
{{- end }}
