# Additional hosts and ports to add to the gateway
# Configure using --values myhosts.yaml

# This file can be used to expose Istio internal components - you should
# create your own file, with the specific list of ports to expose.

# All certificates for TLS are expected to be present in the 'certs' secret,
# matching the hostname.

# TODO: support a wildcard cert
# wildcardCert: example.com

domain: example.com

tcp:
- port: 8000
  name: tcp-iperf3

hosts:
- name: prom11
  dest: prometheus.istio-telemetry.svc.cluster.local
  port: 9090

- name: prom
  dest: prometheus.istio-system.svc.cluster.local
  port: 9090

- name: grafana
  dest: grafana.istio-telemetry.svc.cluster.local
  port: 3000

- name: trace
  dest: tracing.istio-system.svc.cluster.local
  port: 80

- name: pilot11
  dest: istio-pilot.istio-pilot11.svc.cluster.local
  port: 8080

- name: pilot10
  dest: istio-pilot.istio-pilot10.svc.cluster.local
  port: 8080

- name: pilot
  dest: istio-pilot.istio-system.svc.cluster.local
  port: 8080

- name: fortio11
  dest: fortiotls.fortio11.svc.cluster.local
  port: 8080

#
