dependencies:
  - name: security
    version: 1.1.0
    condition: security.enabled
  - name: nodeagent
    version: 1.1.0
    condition: nodeagent.enabled
  - name: certmanager
    version: 1.1.0
    condition: certmanager.enabled
