#
# pilot configuration
#
enabled: true
replicaCount: 1
autoscaleMin: 1
autoscaleMax: 5
image: pilot
sidecar: true
traceSampling: 1.0
# Resources for a small pilot install
resources:
  requests:
    cpu: 500m
    memory: 2048Mi
env:
  GODEBUG: gctrace=2
cpu:
  targetAverageUtilization: 80

