apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: servicegraph
  namespace: {{ .Release.Namespace }}
spec:
  host: servicegraph.{{ .Release.Namespace }}
  trafficPolicy:
    tls:
      mode: DISABLE
