apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: istio-policy-admin-role-binding-{{ .Release.Namespace }}
  labels:
    app: istio-policy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-policy
subjects:
  - kind: ServiceAccount
    name: istio-mixer-service-account
    namespace: {{ .Release.Namespace }}
