dependencies:
  - name: galley
    version: 1.1.0
    condition: galley.enabled
  - name: pilot
    version: 1.1.0
    condition: pilot.enabled
  - name: sidecarInjectorWebhook
    version: 1.1.0
    condition: sidecarInjectorWebhook.enabled
