replicaCount: 1
autoscaleMin: 1
autoscaleMax: 5

# Can be a full hub/image:tag
image: pilot

# Use a sidecar for pilot
sidecar: false

traceSampling: 10.0

# Resources for a small pilot install
resources:
  requests:
    cpu: 500m
    memory: 2048Mi


env:
  GODEBUG: gctrace=2

cpu:
  targetAverageUtilization: 80

mixer:
  # Will not define mixerCheckServer and mixerReportServer
  enabled: true

# Don't attempt to set ingress controller.
# The controller can only be enabled in one namespace.
ingress:
  enabled: false

# Use different namespaces for telemetry and policy.
telemetryNamespace: istio-telemetry
policyNamespace: istio-policy

# TODO: operator or pilot code to auto-configure networks if it
# can discover the endpoints.
meshNetworks:
  #networks: {}

  networks:
    weekly10:
      gateways:
      - address: 35.224.222.243
        port: 15443
      endpoints:
      - fromRegistry: weekly10
    costin11:
      gateways:
      - address: 35.236.6.124
        port: 15443
      endpoints:
      - fromRegistry: costin11

  #
  # Example:
  #
  # networks:
  #   network1:
  #     endpoints:
  #     - fromCidr: "192.168.0.1/24"
  #     gateways:
  #     - address: 1.1.1.1
  #       port: 80
  #   network2:
  #     endpoints:
  #     - fromRegistry: reg1
  #     gateways:
  #     - registryServiceName: reg1
  #       port: 443


# Only used if installing pilot standalone. When imported, the global from istio
# is used.
global:
  hub: gcr.io/istio-release
  tag: release-1.1-latest-daily

  # IF true, no calls to istio-policy will be made
  disablePolicyChecks: false

  policyCheckFailOpen: true

  enableTracing: true

  # Default setting for sidecar access logs.
  accessLogFile: /dev/null

  controlPlaneSecurityEnabled: false

  k8sIngressSelector: ingress
  configMap: true
  meshExpansion:
    enabled: true

  proxy:
    resources: {}
    tracer: "none"
    concurrency: 4

  # SDS enabled. IF set to true, mTLS certificates for the sidecars will be
  # distributed through the SecretDiscoveryService instead of using K8S secrets to mount the certificates.
  sds:
    enabled: false
    udsPath: ""
    enableTokenMount: false

